package:
    name: ase
    version: "3.15.0"

source:
    path: .

requirements:
    build:
        - python
        - flask
        - matplotlib
        - numpy
        - scipy
    run:
        - python
        - flask
        - matplotlib
        - numpy
        - scipy
